### ISSUE TITLE
TODO for college-chooser launch

### ISSUE THREAD

**Issue by yourcelf** [AdmitHub/college-chooser#4]
Function
 - [ ] Full q/a display in prospective detail (officers), counselor view (high school counselors), and user profile (students).
 - [ ] Get images to s3 and use them
 - [ ] Handle archived matches on college officers view
 - [ ] Move data permission question into form flow (with Kirk/Andrew's copy)
 - [ ] Update college partners list to include message counts by date range for billing
 - [ ] Add introductory message from AdmitHub on first match
 - [ ] Workflow initiation for cold-texts
 - [ ] Thorough testing of text transport
 - [ ] Add zip code data and score adjustments

Detail
 - [ ] Functional front page experience for college officers or high school counselors
 - [ ] Fix login redirects (clicking "login" takes you nowhere)
 - [ ] Notifications in user menu or toolbar
 - [ ] Fix gravatars
 - [ ] Page titles everywhere

All the high school counselor things:
 - [ ] Associate students with highschools. Handle onboarding based on incoming phone number.
 - [ ] Counselor list and detail views for students.
 - [ ] Counselor "Verification" ?
 - [ ] Counselor messaging ?

**Comment by AndrewMagliozzi** [comment]
If you put lorem ipsum text for the "page title tags" and other SEO stuff, I can fix them

If you do the basics on the footers, Jordan and I can handle the rest of the styling.

Don't worry about counselor 'verification' or 'messaging' right now.  Let's just see if we can get the basics working so they can observe their students...

Hope that helps.

**Comment by AndrewMagliozzi** [comment]
CC-NC license is for the forum only.

**Comment by jordantomax** [comment]
Still not seeing school images or logos.

**Comment by yourcelf** [comment]
Check the image sources. If they say linkedin, you don't have the latest dump.

**Comment by AndrewMagliozzi** [comment]
you might have to reset your database and try again with the data dump.  I
see all the logos and banners.

**Comment by jordantomax** [comment]
No LinkedIn, the image sources are not rendering at all. Is there a place where I can get the latest dump

**Comment by jordantomax** [comment]
Latest dump didn't fix the problem

**Comment by AndrewMagliozzi** [comment]
before you add that dump, do a "meteor reset" first.

**Comment by jordantomax** [comment]
Presto!

**Comment by AndrewMagliozzi** [comment]
sweet!

**Comment by jordantomax** [comment]
signup and register social buttons read 'configure'

**Comment by jordantomax** [comment]
how to change 'login forbidden' error text?

**Comment by AndrewMagliozzi** [comment]
I will configure those social login buttons when we deploy the site.
Ignore for now on local host

**Comment by yourcelf** [comment]
> how to change 'login forbidden' error text?

See [``packages/admithub-auth/lib/config.js``](https://github.com/AdmitHub/admithub-auth/blob/master/lib/config.js#L84) and https://github.com/meteor-useraccounts/core/blob/master/Guide.md#configuring-texts

**Comment by jordantomax** [comment]
Sweet, thanks.

@AndrewMagliozzi, any problem with moving 'prospective students' into the college officer user navigation?

**Comment by AndrewMagliozzi** [comment]
Hey Jordan, I'm not sure I understand the question.

**Comment by jordantomax** [comment]
currently the college officer navigates to a list of prospective students by first visiting his profile. I'm proposing we move it into the main navigation to expose it more clearly
